### ISSUE TITLE
API level 21 is not working due to incorrect shadows

### ISSUE THREAD

**Issue by bangarharshit** [bangarharshit/RoboOleaster#2]
Trace:
```
java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V
	at com.android.internal.util.GrowingArrayUtils.insert(GrowingArrayUtils.java:135)
	at android.util.SparseIntArray.put(SparseIntArray.java:143)
	at android.view.RenderNodeAnimator$1.__constructor__(RenderNodeAnimator.java:68)
	at android.view.RenderNodeAnimator$1.<init>(RenderNodeAnimator.java)
	at android.view.RenderNodeAnimator.__staticInitializer__(RenderNodeAnimator.java:67)
	at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:263)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:56)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:116)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:20)
	at android.view.RenderNodeAnimator.<clinit>(RenderNodeAnimator.java)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:158)
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:173)
	at org.robolectric.shadows.ShadowRenderNodeAnimator.reset(ShadowRenderNodeAnimator.java:33)
	at org.robolectric.Shadows.reset(Shadows.java:1662)
	at org.robolectric.Robolectric.reset(Robolectric.java:42)
	at org.robolectric.android.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:45)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.beforeTest(OleasterRobolectricRunner.java:104)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:273)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:57)
	at org.robolectric.internal.RoboOleaster.runChild(RoboOleaster.java:171)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.internal.RoboOleaster.runChild(RoboOleaster.java:171)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: An exception occurred while running invokable: Can't create handler inside thread that has not called Looper.prepare()
	at com.mscharhag.oleaster.runner.OleasterRunner.lambda$runInvokables$1(OleasterRunner.java:168)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.mscharhag.oleaster.runner.OleasterRunner.runInvokables(OleasterRunner.java:164)
	at com.mscharhag.oleaster.runner.OleasterRunner.runBeforeEachCallbacks(OleasterRunner.java:121)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:287)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:57)
	... 21 more
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.__constructor__(Handler.java:200)
	at android.os.Handler.<init>(Handler.java)
	at android.app.Activity.__constructor__(Activity.java:793)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:232)
	at org.robolectric.internal.bytecode.ShadowImpl.invokeConstructor(ShadowImpl.java:71)
	at org.robolectric.shadow.api.Shadow.invokeConstructor(Shadow.java:66)
	at org.robolectric.shadows.ShadowActivity.__constructor__(ShadowActivity.java:80)
	at android.app.Activity.<init>(Activity.java)
	at com.example.harshitbangar.testapp.MainActivity.<init>(MainActivity.java:8)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:322)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:98)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:94)
	at com.example.harshitbangar.testapp.MainActivityTest.lambda$null$0(MainActivityTest.java:35)
	at com.mscharhag.oleaster.runner.OleasterRunner.lambda$runInvokables$1(OleasterRunner.java:166)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.mscharhag.oleaster.runner.OleasterRunner.runInvokables(OleasterRunner.java:164)
	at com.mscharhag.oleaster.runner.OleasterRunner.runBeforeEachCallbacks(OleasterRunner.java:121)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:287)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:57)
	at org.robolectric.internal.RoboOleaster.runChild(RoboOleaster.java:171)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	... 1 more
java.lang.NoClassDefFoundError: Could not initialize class android.view.RenderNodeAnimator
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:158)
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:173)
	at org.robolectric.shadows.ShadowRenderNodeAnimator.reset(ShadowRenderNodeAnimator.java:33)
	at org.robolectric.Shadows.reset(Shadows.java:1662)
	at org.robolectric.Robolectric.reset(Robolectric.java:42)
	at org.robolectric.android.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:45)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.beforeTest(OleasterRobolectricRunner.java:104)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:273)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.internal.RoboOleaster.runChild(RoboOleaster.java:171)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.internal.RoboOleaster.runChild(RoboOleaster.java:171)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: An exception occurred while running invokable: Can't create handler inside thread that has not called Looper.prepare()
	at com.mscharhag.oleaster.runner.OleasterRunner.lambda$runInvokables$1(OleasterRunner.java:168)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.mscharhag.oleaster.runner.OleasterRunner.runInvokables(OleasterRunner.java:164)
	at com.mscharhag.oleaster.runner.OleasterRunner.runBeforeEachCallbacks(OleasterRunner.java:121)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:287)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:57)
	... 21 more
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.__constructor__(Handler.java:200)
	at android.os.Handler.<init>(Handler.java)
	at android.app.Activity.__constructor__(Activity.java:793)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:232)
	at org.robolectric.internal.bytecode.ShadowImpl.invokeConstructor(ShadowImpl.java:71)
	at org.robolectric.shadow.api.Shadow.invokeConstructor(Shadow.java:66)
	at org.robolectric.shadows.ShadowActivity.__constructor__(ShadowActivity.java:80)
	at android.app.Activity.<init>(Activity.java)
	at com.example.harshitbangar.testapp.MainActivity.<init>(MainActivity.java:8)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:322)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:98)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:94)
	at com.example.harshitbangar.testapp.MainActivityTest.lambda$null$0(MainActivityTest.java:35)
	at com.mscharhag.oleaster.runner.OleasterRunner.lambda$runInvokables$1(OleasterRunner.java:166)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.mscharhag.oleaster.runner.OleasterRunner.runInvokables(OleasterRunner.java:164)
	at com.mscharhag.oleaster.runner.OleasterRunner.runBeforeEachCallbacks(OleasterRunner.java:121)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:287)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:57)
	at org.robolectric.internal.RoboOleaster.runChild(RoboOleaster.java:171)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	... 1 more
java.lang.NoClassDefFoundError: Could not initialize class android.view.RenderNodeAnimator
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:158)
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:173)
	at org.robolectric.shadows.ShadowRenderNodeAnimator.reset(ShadowRenderNodeAnimator.java:33)
	at org.robolectric.Shadows.reset(Shadows.java:1662)
	at org.robolectric.Robolectric.reset(Robolectric.java:42)
	at org.robolectric.android.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:45)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.beforeTest(OleasterRobolectricRunner.java:104)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:273)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.internal.RoboOleaster.runChild(RoboOleaster.java:171)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.internal.RoboOleaster.runChild(RoboOleaster.java:171)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: An exception occurred while running invokable: Can't create handler inside thread that has not called Looper.prepare()
	at com.mscharhag.oleaster.runner.OleasterRunner.lambda$runInvokables$1(OleasterRunner.java:168)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.mscharhag.oleaster.runner.OleasterRunner.runInvokables(OleasterRunner.java:164)
	at com.mscharhag.oleaster.runner.OleasterRunner.runBeforeEachCallbacks(OleasterRunner.java:121)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:287)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:57)
	... 21 more
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.__constructor__(Handler.java:200)
	at android.os.Handler.<init>(Handler.java)
	at android.app.Activity.__constructor__(Activity.java:793)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:232)
	at org.robolectric.internal.bytecode.ShadowImpl.invokeConstructor(ShadowImpl.java:71)
	at org.robolectric.shadow.api.Shadow.invokeConstructor(Shadow.java:66)
	at org.robolectric.shadows.ShadowActivity.__constructor__(ShadowActivity.java:80)
	at android.app.Activity.<init>(Activity.java)
	at com.example.harshitbangar.testapp.MainActivity.<init>(MainActivity.java:8)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:322)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:98)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:94)
	at com.example.harshitbangar.testapp.MainActivityTest.lambda$null$0(MainActivityTest.java:35)
	at com.mscharhag.oleaster.runner.OleasterRunner.lambda$runInvokables$1(OleasterRunner.java:166)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.mscharhag.oleaster.runner.OleasterRunner.runInvokables(OleasterRunner.java:164)
	at com.mscharhag.oleaster.runner.OleasterRunner.runBeforeEachCallbacks(OleasterRunner.java:121)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:287)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:57)
	at org.robolectric.internal.RoboOleaster.runChild(RoboOleaster.java:171)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	... 1 more
```

The test works perfectly with RobolectricTestRunner. Instrumentation config is incorrectly loaded.

**Comment by bangarharshit** [comment]
Fixed with https://github.com/bangarharshit/RoboOleaster/commit/76f9a8e6e09c0a0fb5240496e479b1e1a41e7ec4
