### ISSUE TITLE
API - V21+ Not working due to missing styles

### ISSUE THREAD

**Issue by bangarharshit** [bangarharshit/RoboOleaster#4]
Trace:
```
com.example.harshitbangar.testapp.MainActivityTest
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.internal.RoboOleaster.runChild(RoboOleaster.java:169)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: An exception occurred while running invokable: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at com.mscharhag.oleaster.runner.OleasterRunner.lambda$runInvokables$1(OleasterRunner.java:168)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.mscharhag.oleaster.runner.OleasterRunner.runInvokables(OleasterRunner.java:164)
	at com.mscharhag.oleaster.runner.OleasterRunner.runBeforeEachCallbacks(OleasterRunner.java:121)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:287)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:57)
	... 21 more
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:354)
	at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
	at com.example.harshitbangar.testapp.MainActivity.onCreate(MainActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:232)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:73)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:366)
	at org.robolectric.shadows.CoreShadowsAdapter$1.runPaused(CoreShadowsAdapter.java:27)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:70)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:80)
	at com.example.harshitbangar.testapp.MainActivityTest.lambda$null$0(MainActivityTest.java:35)
	at com.mscharhag.oleaster.runner.OleasterRunner.lambda$runInvokables$1(OleasterRunner.java:166)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.mscharhag.oleaster.runner.OleasterRunner.runInvokables(OleasterRunner.java:164)
	at com.mscharhag.oleaster.runner.OleasterRunner.runBeforeEachCallbacks(OleasterRunner.java:121)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:287)
	at com.mscharhag.oleaster.runner.OleasterRobolectricRunner.runChild(OleasterRobolectricRunner.java:57)
	at org.robolectric.internal.RoboOleaster.runChild(RoboOleaster.java:169)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	... 1 more

Process finished with exit code 0
```

**Comment by bangarharshit** [comment]
Fixed with d730d1b99a563bb04b6d731bbc06d4a1d3a95988
